### ISSUE TITLE
pi-install.sh problem

### ISSUE THREAD

**Issue by AstroKeith** [WimDeMeester/eFinder#28]
poetry fails to install.
Path to astrometry/bin doesnt get added.
[poetry-installer-error-ejja8mll.log](https://github.com/WimDeMeester/eFinder/files/10152638/poetry-installer-error-ejja8mll.log)

**Comment by WimDeMeester** [comment]
Tested on a new micro SD card and the script runs without problems.  Added a few clarifications in the README.md documentation and enabled the vncserver in the pi-install.sh script.

**Comment by AstroKeith** [comment]
Excellent work!
